/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic.appointment.system;

import static java.awt.Color.blue;



/**
 *
 * @author Aeron
 */
public class ClinicJframe extends javax.swing.JFrame {
    

    /**
     * Creates new form ClinicJframe
     */
    
    public ClinicJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    public void setProgressBarValue(int value) {
        bar.setValue(value);
    }

    public void setProgressLabelText(String text) {
        progress.setText(text);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        progress = new javax.swing.JLabel();
        LoadingText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        toApprove = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar.setBackground(new java.awt.Color(255, 255, 255));
        bar.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        bar.setForeground(new java.awt.Color(51, 187, 224));
        getContentPane().add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 470, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic/appointment/system/S2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 259, 249));

        progress.setFont(new java.awt.Font("Century Gothic", 0, 21)); // NOI18N
        progress.setForeground(new java.awt.Color(0, 0, 0));
        progress.setText("%");
        getContentPane().add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 62, -1));

        LoadingText.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        LoadingText.setForeground(new java.awt.Color(0, 0, 0));
        LoadingText.setText("Loading Module...");
        getContentPane().add(LoadingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        toApprove.setBackground(java.awt.SystemColor.control);
        toApprove.setFont(new java.awt.Font("Century Gothic", 1, 25)); // NOI18N
        toApprove.setForeground(new java.awt.Color(204, 204, 204));
        toApprove.setText("x");
        toApprove.setBorder(null);
        toApprove.setContentAreaFilled(false);
        toApprove.setFocusPainted(false);
        toApprove.setMargin(new java.awt.Insets(0, 0, 0, 0));
        toApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toApproveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addComponent(toApprove)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(toApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 398, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toApproveActionPerformed
        System.exit(0);
    }//GEN-LAST:event_toApproveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    ClinicJframe Cframe = new ClinicJframe();
    Cframe.setVisible(true);
    Cframe.pack();
    Cframe.setLocationRelativeTo(null);

    // Start a new thread for the loading process
    new Thread(() -> {
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(10);
                Cframe.bar.setValue(i);
                Cframe.progress.setText(Integer.toString(i) + "%");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Close the loading screen and open the main application window
            Cframe.dispose();
            MainPage n = new MainPage();
            n.setVisible(true);
        }
    }).start();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoadingText;
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel progress;
    private javax.swing.JButton toApprove;
    // End of variables declaration//GEN-END:variables
}
