/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic.appointment.system;

/**
 *
 * @author Aeron
 */
  
public class Login1 extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */ //for ENTEREDNAME
    
    public Login1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        usernamefield = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        LOGINdesign = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        usernamefield2 = new javax.swing.JTextField();
        username2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        passwordfield1 = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        username3 = new javax.swing.JLabel();
        toAdmin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        usernamefield.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        usernamefield.setBorder(null);
        usernamefield.setInheritsPopupMenu(true);
        usernamefield.setMargin(new java.awt.Insets(10, 10, 10, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernamefield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        username.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        username.setForeground(new java.awt.Color(51, 51, 51));
        username.setText("Username");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGINdesign.setFont(new java.awt.Font("Century Gothic", 1, 35)); // NOI18N
        LOGINdesign.setForeground(new java.awt.Color(51, 51, 51));
        LOGINdesign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGINdesign.setText("LOGIN");
        getContentPane().add(LOGINdesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 106, 151, -1));

        username1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        username1.setForeground(new java.awt.Color(51, 51, 51));
        username1.setText("Username");
        getContentPane().add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 119, 31));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        usernamefield2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        usernamefield2.setBorder(null);
        usernamefield2.setInheritsPopupMenu(true);
        usernamefield2.setMargin(new java.awt.Insets(10, 10, 10, 10));
        usernamefield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefield2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(usernamefield2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernamefield2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        username2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        username2.setForeground(new java.awt.Color(51, 51, 51));
        username2.setText("Password");
        getContentPane().add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 119, 31));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        passwordfield1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        passwordfield1.setForeground(new java.awt.Color(0, 0, 0));
        passwordfield1.setBorder(null);
        passwordfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfield1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(passwordfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(passwordfield1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        loginbutton.setBackground(new java.awt.Color(51, 187, 224));
        loginbutton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setText("LOGIN");
        loginbutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 380, 41));

        username3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        username3.setForeground(new java.awt.Color(51, 51, 51));
        username3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username3.setText("Login as");
        getContentPane().add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 80, 31));

        toAdmin.setBackground(java.awt.SystemColor.control);
        toAdmin.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        toAdmin.setForeground(new java.awt.Color(51, 187, 224));
        toAdmin.setText("Administrator");
        toAdmin.setBorder(null);
        toAdmin.setContentAreaFilled(false);
        toAdmin.setFocusPainted(false);
        toAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        toAdmin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        toAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toAdminActionPerformed(evt);
            }
        });
        getContentPane().add(toAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 382, -1, 49));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        exit.setBackground(java.awt.SystemColor.control);
        exit.setFont(new java.awt.Font("Century Gothic", 1, 25)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 204, 204));
        exit.setText("x");
        exit.setBorder(null);
        exit.setContentAreaFilled(false);
        exit.setFocusPainted(false);
        exit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(482, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void passwordfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfield1ActionPerformed
    
    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        String enteredUsername = usernamefield2.getText(); //new
        String enteredUsername2 = usernamefield2.getText();
        
        ClinicJframe Cframe = new ClinicJframe();
        Cframe.setVisible(true);
        Cframe.pack();
        Cframe.setLocationRelativeTo(null);

    new Thread(() -> {
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(10);
                Cframe.setProgressBarValue(i);
                Cframe.setProgressLabelText(Integer.toString(i) + "%");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            Cframe.dispose();
            UserPage toUser = new UserPage(enteredUsername); // Pass the username to the constructor
            toUser.setVisible(true);
        }
    }).start();

    this.setVisible(false);      
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void toAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toAdminActionPerformed
        Login2 toAdmin = new Login2();
        toAdmin.setVisible(true);
        toAdmin.pack();
        toAdmin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_toAdminActionPerformed


    private void usernamefield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefield2ActionPerformed

        
        
    }//GEN-LAST:event_usernamefield2ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGINdesign;
    private javax.swing.JButton exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPasswordField passwordfield1;
    private javax.swing.JButton toAdmin;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JTextField usernamefield;
    private javax.swing.JTextField usernamefield2;
    // End of variables declaration//GEN-END:variables
}
